### PR TITLE
Add rights management support

### PR DESCRIPTION
**Pull request by chorig9**
This updates abi and adjusts client application to DistributedWiki/smart-contracts/pull/13.

I changed ropsten to kovan (I hope temporarily) because of huge latency in tx processing.

---
This change is [Reviewable](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29)

### CODE REVIEW

**Review by pkobielak — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29)* status: all files reviewed, 7 unresolved discussions (waiting on @chorig9)

___
*[blockchain/blockchain_db.py, line 71 at r1](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29#-LQVbhxxBGe7z5IkD9BO:-LQVbhxxBGe7z5IkD9BP:b-9rwqvp) ([raw file](https://github.com/distributedwiki/wiki-python-client/blob/5a38cf399d3648de91dd58970a99eec1172c9d52/blockchain/blockchain_db.py#L71)):*
> ```Python
>         """
>         :param title: string
>         :param ID: bytes
> ```

Missing docstring for new variable `authorized`. Please explain what it does.
___
*[client/client.py, line 48 at r1](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29#-LQVc_K16zfukfYge-9u:-LQVc_K16zfukfYge-9v:b-e4zpgf) ([raw file](https://github.com/distributedwiki/wiki-python-client/blob/5a38cf399d3648de91dd58970a99eec1172c9d52/client/client.py#L48)):*
> ```Python
> 
>         if allow_author:
>             authorized.append(self.blockchain_db.get_account_address())
> ```

I think adding permission should be logged in some way. Please add some logs so we can track this.
___
*[client/gui/add_authorized.py, line 2 at r1](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29#-LQVcvFf47hkp7kF85Kp:-LQVcvFf47hkp7kF85Kq:bdoetsh) ([raw file](https://github.com/distributedwiki/wiki-python-client/blob/5a38cf399d3648de91dd58970a99eec1172c9d52/client/gui/add_authorized.py#L2)):*
> ```Python
> from PyQt5.QtCore import QSize
> from PyQt5.QtWidgets import QMainWindow, QListWidget, QPushButton, QLineEdit, \
> ```

Each class import should be in separate line. Laso please optimise imports if you use pycharm Ctrl+Alt+O on the file or on project dir in project explorer to optimise all unoptimised files.
___
*[client/gui/add_authorized.py, line 10 at r1](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29#-LQVdjOa9Y5n87EY9rM0:-LQVdjOa9Y5n87EY9rM1:buom7hg) ([raw file](https://github.com/distributedwiki/wiki-python-client/blob/5a38cf399d3648de91dd58970a99eec1172c9d52/client/gui/add_authorized.py#L10)):*
> ```Python
> 
> 
> class AddAuthorized(QMainWindow):
> ```

I would like to see at least one small docstring here explaining what this class does.
___
*[client/gui/add_authorized.py, line 44 at r1](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29#-LQVdW9k2FXSYgRvwpKc:-LQVdW9lEsWP2h67fxk5:bqcm93r) ([raw file](https://github.com/distributedwiki/wiki-python-client/blob/5a38cf399d3648de91dd58970a99eec1172c9d52/client/gui/add_authorized.py#L44)):*
> ```
> self.ok.move(self.width() / 2 - self.ok.width() / 2, self.address.height() + self.list.height() + 3 * MARGIN)
> ```
This line is over <79 and should cut somewhere and moved to the next line.
___
*[client/gui/gui.py, line 297 at r1](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29#-LQVe7DZAnzAdjzDbthJ:-LQVe7DZAnzAdjzDbthK:bd16or2) ([raw file](https://github.com/distributedwiki/wiki-python-client/blob/5a38cf399d3648de91dd58970a99eec1172c9d52/client/gui/gui.py#L297)):*
> ```Python
>         print(title)
>         print(authorized)
>         print(allow_author)
> ```

I believe those 'prints' can be changed to nice looking and useful `LOG.debug(...)` call.
___
*[client/gui/gui_conf.py, line 13 at r1](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29#-LQVeNz3-yoRn74kXdfW:-LQVeNz3-yoRn74kXdfX:b-qda674) ([raw file](https://github.com/distributedwiki/wiki-python-client/blob/5a38cf399d3648de91dd58970a99eec1172c9d52/client/gui/gui_conf.py#L13)):*
> ```Python
> ADD_AUTHORIZED_HEIGHT = 200
> 
> WINDOW_TITLE = 'Distributed Wikipedia Python Client'
> ```

By the way, we should change the project naming in the near future.

**Review by chorig9 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29)* status: 3 of 9 files reviewed, 7 unresolved discussions (waiting on @Dual2Core)

___
*[blockchain/blockchain_db.py, line 71 at r1](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29#-LQVbhxxBGe7z5IkD9BO:-LQVg_hV-s0d1IQD0drh:b-896fix) ([raw file](https://github.com/distributedwiki/wiki-python-client/blob/5a38cf399d3648de91dd58970a99eec1172c9d52/blockchain/blockchain_db.py#L71)):*
<details><summary><i>Previously, Dual2Core wrote…</i></summary><blockquote>

Missing docstring for new variable `authorized`. Please explain what it does.
</blockquote></details>

Done.
___
*[client/client.py, line 48 at r1](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29#-LQVc_K16zfukfYge-9u:-LQVgoKXAABGGQ1dXXjB:b-896fix) ([raw file](https://github.com/distributedwiki/wiki-python-client/blob/5a38cf399d3648de91dd58970a99eec1172c9d52/client/client.py#L48)):*
<details><summary><i>Previously, Dual2Core wrote…</i></summary><blockquote>

I think adding permission should be logged in some way. Please add some logs so we can track this.
</blockquote></details>

Done.
___
*[client/gui/add_authorized.py, line 2 at r1](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29#-LQVcvFf47hkp7kF85Kp:-LQVh6ffDFLsMbUi4CNd:b-896fix) ([raw file](https://github.com/distributedwiki/wiki-python-client/blob/5a38cf399d3648de91dd58970a99eec1172c9d52/client/gui/add_authorized.py#L2)):*
<details><summary><i>Previously, Dual2Core wrote…</i></summary><blockquote>

Each class import should be in separate line. Laso please optimise imports if you use pycharm Ctrl+Alt+O on the file or on project dir in project explorer to optimise all unoptimised files.
</blockquote></details>

Done.
___
*[client/gui/add_authorized.py, line 10 at r1](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29#-LQVdjOa9Y5n87EY9rM0:-LQVhKxPDZhQHF4D-U6B:b-896fix) ([raw file](https://github.com/distributedwiki/wiki-python-client/blob/5a38cf399d3648de91dd58970a99eec1172c9d52/client/gui/add_authorized.py#L10)):*
<details><summary><i>Previously, Dual2Core wrote…</i></summary><blockquote>

I would like to see at least one small docstring here explaining what this class does.
</blockquote></details>

Done.
___
*[client/gui/add_authorized.py, line 44 at r1](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29#-LQVdW9k2FXSYgRvwpKc:-LQVhO-A8o2UxB9iEjVR:b-896fix) ([raw file](https://github.com/distributedwiki/wiki-python-client/blob/5a38cf399d3648de91dd58970a99eec1172c9d52/client/gui/add_authorized.py#L44)):*
<details><summary><i>Previously, Dual2Core wrote…</i></summary><blockquote>

> ```
> self.ok.move(self.width() / 2 - self.ok.width() / 2, self.address.height() + self.list.height() + 3 * MARGIN)
> ```
This line is over <79 and should cut somewhere and moved to the next line.
</blockquote></details>

Done.
___
*[client/gui/gui.py, line 297 at r1](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29#-LQVe7DZAnzAdjzDbthJ:-LQVhfcL-DKiGPgb2hsU:b-896fix) ([raw file](https://github.com/distributedwiki/wiki-python-client/blob/5a38cf399d3648de91dd58970a99eec1172c9d52/client/gui/gui.py#L297)):*
<details><summary><i>Previously, Dual2Core wrote…</i></summary><blockquote>

I believe those 'prints' can be changed to nice looking and useful `LOG.debug(...)` call.
</blockquote></details>

Done.
___
*[client/gui/gui_conf.py, line 13 at r1](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29#-LQVeNz3-yoRn74kXdfW:-LQVhhme60EjHGTMZGrU:b-ecsxrc) ([raw file](https://github.com/distributedwiki/wiki-python-client/blob/5a38cf399d3648de91dd58970a99eec1172c9d52/client/gui/gui_conf.py#L13)):*
<details><summary><i>Previously, Dual2Core wrote…</i></summary><blockquote>

By the way, we should change the project naming in the near future.
</blockquote></details>

Right, I will do separate PR.

**Review by pkobielak — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29)* status: all files reviewed, 2 unresolved discussions (waiting on @chorig9)

___
*[client/client_conf.py, line 4 at r2](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29#-LQVojasBEzKPqU7kY_9:-LQVojasBEzKPqU7kY_A:b4cwvl4) ([raw file](https://github.com/distributedwiki/wiki-python-client/blob/a39d9e4497b2ea0b25c88bd4f408310de74d8cc1/client/client_conf.py#L4)):*
> ```Python
> DEV_TOP_LEVEL_ADDRESS = '0xA4A6B74da1317751F2ee0bFBFE2FeBd3a9E026f1'
> DEV_PRIVATE_KEY="fa9bb03a928082551c83892a315850fe659dafd726aa61f40286ec09fac725a7"
> DEV_INFURA="https://ropsten.infura.io/OQe96S6X8l5PM7NexvCM"
> ```

back to ropsten? is it intended?
___
*[client/gui/add_authorized.py, line 44 at r1](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29#-LQVdW9k2FXSYgRvwpKc:-LQVouD6C4gu-VlMuAz1:b-ehuk7l) ([raw file](https://github.com/distributedwiki/wiki-python-client/blob/5a38cf399d3648de91dd58970a99eec1172c9d52/client/gui/add_authorized.py#L44)):*
<details><summary><i>Previously, chorig9 (Igor Chorążewicz) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I cant see that this line has changed to be honest.

**Review by chorig9 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @Dual2Core)

___
*[client/client_conf.py, line 4 at r2](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29#-LQVojasBEzKPqU7kY_9:-LRYlL9nAKOQi7NntOju:b9ug7pt) ([raw file](https://github.com/distributedwiki/wiki-python-client/blob/a39d9e4497b2ea0b25c88bd4f408310de74d8cc1/client/client_conf.py#L4)):*
<details><summary><i>Previously, Dual2Core wrote…</i></summary><blockquote>

back to ropsten? is it intended?
</blockquote></details>

Yes, I added extra configuration for kovan in separate file.

**Review by pkobielak — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pkobielak — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/distributedwiki/wiki-python-client/29#-:-LSPuZEp0ppKveiIZ5sS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
